### ISSUE TITLE
Inference on custom dataset and visualization

### ISSUE THREAD

**Issue by YunxuanMao** [ctu-vras/let-it-flow#1]
Hi, thank you for your excellent work. Can you give me some instructions on how to inference on my own dataset and how to visualize the inference results?

**Comment by vacany** [comment]
Hello,

thank you for your interest in our work! The simplest approach would be, to use the script [run_optimization.py](https://github.com/ctu-vras/let-it-flow/blob/master/run_optimization.py) and load list of your point clouds synchronized with odometry from Kiss-ICP into the variable **global_list** in [the script](https://github.com/ctu-vras/let-it-flow/blob/a1a0be94645579173691348852763d0e5ce69680/run_optimization.py#L68). Then on the above line comment the **sample_argoverse** function and store only [variables](https://github.com/ctu-vras/let-it-flow/blob/a1a0be94645579173691348852763d0e5ce69680/run_optimization.py#L117) that that remain after commenting out the **sample_argoverse** function.

As for visualization of the results, I recommend Open3D library and visualize point cloud and flow from the resulting npz file as normals of the Open3D Point Cloud class.

**Comment by YunxuanMao** [comment]
Thank you for your reply!
